### ISSUE TITLE
Add next method to cursor

### ISSUE THREAD

**Issue by JPDevelop** [michaelkryukov/mongomock_motor#26]
Motor has an async `next()` [method](https://motor.readthedocs.io/en/stable/api-asyncio/cursors.html#motor.motor_asyncio.AsyncIOMotorCursor.next) which this library does not implement.

**Comment by michaelkryukov** [comment]
Fair remark. I've created #28 with a more elegant implementation than #27 (also with some internal tweaks and more tests). I'll merge it and close №26, #27, if that's ok

**Comment by JPDevelop** [comment]
Sounds great, thanks :)
