### ISSUE TITLE
 __new__() got an unexpected keyword argument 'datetime_conversion'

### ISSUE THREAD

**Issue by DoanLoi** [michaelkryukov/mongomock_motor#37]
def is_supported(custom_codec_options):
    
        if not custom_codec_options:
            return None
    
>       return CodecOptions(**custom_codec_options._asdict())
E       TypeError: __new__() got an unexpected keyword argument 'datetime_conversion'

**Comment by michaelkryukov** [comment]
https://github.com/mongomock/mongomock/issues/810
