### ISSUE TITLE
0.0.32 release has broken the project homepage and license information on pypi.org

### ISSUE THREAD

**Issue by skathait** [michaelkryukov/mongomock_motor#57]
With the latest release https://pypi.org/project/mongomock-motor/ license and project homepage links are broken on pypi.
The license check info on the latest release using Pypi APIs categorises this as an Unknown license.

https://pypi.org/project/mongomock-motor/

**Comment by michaelkryukov** [comment]
Yep, thanks for noticing. Everything should be correct now
